# Generated by Django 3.2.8 on 2021-10-07 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_match_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_points', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
                ('user_match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_match', to='core.matches')),
            ],
        ),
        migrations.CreateModel(
            name='match_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_match', to='core.matches')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_player', to='core.players')),
            ],
        ),
    ]
