# Generated by Django 3.2.8 on 2021-10-07 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_match_player_user_matches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='match_player',
            new_name='MatchPlayer',
        ),
        migrations.RenameModel(
            old_name='user_matches',
            new_name='UserMatches',
        ),
    ]
