# Generated by Django 3.2.8 on 2021-10-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211007_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatches',
            name='user_points',
        ),
    ]
