# Generated by Django 3.2.8 on 2021-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='short_name',
            field=models.CharField(default='hello', max_length=15),
            preserve_default=False,
        ),
    ]
