# Generated by Django 3.2.8 on 2021-10-08 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_match', to='match.matches')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_player', to='player.players')),
            ],
        ),
    ]
